#!/usr/bin/env bash

tmpfile=`mktemp /tmp/aws_up_and_running.XXXXX`
tmpfile="/tmp/aws_up"

cat <<EOF

aws ec2 run-instances \\
            --image-id "ami-0f47053f" \\
            --count 1 \\
            --key-name "mario-dev" \\
            --user-data "file://${HOME}/dev/jmt/sh/user_data_file" \\
            --placement "AvailabilityZone=us-west-2c" \\
            --profile "eops" \\
            --instance-type "m3.xlarge" \\

  web-tier:
            --security-group-ids sg-02cea467 sg-29cea44c \\
            --subnet-id subnet-33638c6a \\
            --private-ip-address 10.0.0.20 \\

  db:
            --security-group-ids sg-02cea467 sg-81d2b8e4 \\
            --subnet-id subnet-43759a1a \\
            --private-ip-address 10.0.0.240 \\
            --private-ip-address 10.0.1.20 \\

  app-tier:
            --security-group-ids sg-02cea467 sg-3bcea45e \\
            --subnet-id subnet-30638c69 \\
            --private-ip-address 10.0.0.100 \\
            --private-ip-address 10.0.2.20 \\

  db:
            --block-device-mapping '[
                  { "DeviceName":"/dev/sdb", "VirtualName":"ephemeral0"},
                  { "DeviceName":"/dev/sdc", "VirtualName":"ephemeral1"},
                  { "DeviceName":"/dev/sdd", "VirtualName":"ephemeral2"},
                  { "DeviceName":"/dev/sde", "VirtualName":"ephemeral3"},
                  { "DeviceName":"/dev/sdf", "Ebs":{"VolumeSize":300}},
                  { "DeviceName":"/dev/sdg", "Ebs":{"VolumeSize":25}},
                  { "DeviceName":"/dev/sdh", "Ebs":{"VolumeSize":10}}
                ]' \\

  web:
            --block-device-mapping '[
                  { "DeviceName":"/dev/sdb", "VirtualName":"ephemeral0"},
                  { "DeviceName":"/dev/sdc", "VirtualName":"ephemeral1"},
                  { "DeviceName":"/dev/sdd", "VirtualName":"ephemeral2"},
                  { "DeviceName":"/dev/sde", "VirtualName":"ephemeral3"},
                  { "DeviceName":"/dev/sdf", "Ebs":{"VolumeSize":100}}
                ]' \\

  app:
            --block-device-mapping '[
                  { "DeviceName":"/dev/sdb", "VirtualName":"ephemeral0"},
                  { "DeviceName":"/dev/sdc", "VirtualName":"ephemeral1"},
                  { "DeviceName":"/dev/sdd", "VirtualName":"ephemeral2"},
                  { "DeviceName":"/dev/sde", "VirtualName":"ephemeral3"}
                ]' \\

            --associate-public-ip-address \\
            | tee $tmpfile | egrep InstanceId | cut -d\\" -f4

export instance_id=\`cat $tmpfile | egrep InstanceId | cut -d\\" -f4\`
aws ec2 describe-instances --instance-ids \$instance_id --query 'Reservations[0].Instances[0].State.Name' --profile eops 
aws ec2 describe-instances --instance-ids \$instance_id --query 'Reservations[0].Instances[0].PublicDnsName' --profile eops 

aws ec2 describe-instances --instance-ids \`cat $tmpfile | egrep InstanceId | cut -d\\" -f4\` --query 'Reservations[0].Instances[0].State.Name' --profile eops 
aws ec2 describe-instances --instance-ids \`cat $tmpfile | egrep InstanceId | cut -d\\" -f4\` --query 'Reservations[0].Instances[0].PublicDnsName' --profile eops 

EOF
exit

