#!/bin/bash -ex
usermod  -l scotty ubuntu
groupmod -n scotty ubuntu
usermod  -d /home/scotty -m scotty
if [ -f /etc/sudoers.d/90-cloudimg-ubuntu ]; then
  mv /etc/sudoers.d/90-cloudimg-ubuntu /etc/sudoers.d/90-cloud-init-users
fi
perl -pi -e "s/ubuntu/scotty/g;" /etc/sudoers.d/90-cloud-init-users

