#!/usr/bin/env bash

# The 'internal' tools -- they should have invoked as 'source <(jmt --inttools)'
cat <<EOF

die()
{
  echo "$@"
  exit_code=1
  if echo "$1" | egrep '^[0-9]+$' 2>&1 > /dev/null; then
    exit_code="$1"
    shift
  fi

  echo "$@" 1>&2 
  exit $exit_code
}

EOF


echo "#This command needs to be sent to 'source', like this: source <(jmt --inttools)"

